langauge: haskell

ghc:
  - 8.0.2

install:
 - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls


script:
 # -v2 provides useful information for debugging
 - cabal configure --enable-tests
 - cabal build

 - cabal test
 - cabal check

 - cabal sdist

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
